### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by mksmanjit** [spring-projects/spring-security-saml-dsl#41]
Hi Team,

I followed all the step mentioned but when i run my application and hit https://localhost:8443/ then browser popped up asking Authentication but when i put my Okata userName and password it is not authenticating, not sure what is the problem.
I have below points:
1) Why my browser popping up with authentication rather than redirecting it to the Okata server.
2) what should be the userName and password for this popping authentication.

 
![image](https://user-images.githubusercontent.com/19969093/30628460-1309a018-9df4-11e7-9856-11e86b15224c.png)

**Comment by rwinch** [comment]
You should not be getting a popup dialog. What is the HTTP response?

**Comment by mksmanjit** [comment]
able to run and now it is reaching to the IDP server page after changing package structure earlier my DemoApplication.java is in com.example.demo and SecurityConfiguration.java and MvcConfig.java in com.example package.

now all three files are in the same package com.example..

but now i am getting another error:

Caused by: org.opensaml.common.SAMLException: Response doesn't have any valid assertion which would pass subject validation
    at org.springframework.security.saml.websso.WebSSOProfileConsumerImpl.processAuthenticationResponse(WebSSOProfileConsumerImpl.java:229)
    at org.springframework.security.saml.SAMLAuthenticationProvider.authenticate(SAMLAuthenticationProvider.java:82)
    ... 27 more
Caused by: org.opensaml.common.SAMLException: Local entity is not the intended audience of the assertion in at least one AudienceRestriction
    at org.springframework.security.saml.websso.WebSSOProfileConsumerImpl.verifyAudience(WebSSOProfileConsumerImpl.java:506)
    at org.springframework.security.saml.websso.WebSSOProfileConsumerImpl.verifyAssertionConditions(WebSSOProfileConsumerImpl.java:458)
    at org.springframework.security.saml.websso.WebSSOProfileConsumerImpl.verifyAssertion(WebSSOProfileConsumerImpl.java:303)
    at org.springframework.security.saml.websso.WebSSOProfileConsumerImpl.processAuthenticationResponse(WebSSOProfileConsumerImpl.java:214)
    ... 28 more

**Comment by mksmanjit** [comment]
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Sep 21 12:04:30 IST 2017
There was an unexpected error (type=Unauthorized, status=401).
Authentication Failed: Error validating SAML message
