### ISSUE TITLE
Unable to serialize session

### ISSUE THREAD

**Issue by loktar** [spring-projects/spring-security-saml-dsl#42]
We're attempting to use `spring-security-saml-dsl` with a Redis session store in our Spring Boot app, and are running into the following exception during the SAML handshake. It appears the `NameIDImpl` class is not serializable, and the session repository classes are expecting it to be.

For reference, we are using Spring Boot v1.5.4.RELEASE and the `org.springframework.session:spring-session-data-redis` v1.3.1.RELEASE library.

Is this a known issue and are there any workarounds? Thanks!

```
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT org.springframework.data.redis.serializer.SerializationException: Cannot serialize; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to serialize object using DefaultSerializer; nested exception is java.io.NotSerializableException: org.opensaml.saml2.core.impl.NameIDImpl
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.serialize(JdkSerializationRedisSerializer.java:93)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.data.redis.core.AbstractOperations.rawHashValue(AbstractOperations.java:171)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.data.redis.core.DefaultHashOperations.putAll(DefaultHashOperations.java:129)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.data.redis.core.DefaultBoundHashOperations.putAll(DefaultBoundHashOperations.java:86)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.session.data.redis.RedisOperationsSessionRepository$RedisSession.saveDelta(RedisOperationsSessionRepository.java:778)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.session.data.redis.RedisOperationsSessionRepository$RedisSession.access$000(RedisOperationsSessionRepository.java:670)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.session.data.redis.RedisOperationsSessionRepository.save(RedisOperationsSessionRepository.java:388)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.session.data.redis.RedisOperationsSessionRepository.save(RedisOperationsSessionRepository.java:245)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.commitSession(SessionRepositoryFilter.java:245)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.access$100(SessionRepositoryFilter.java:217)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:170)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.cloudfoundry.router.ClientCertificateMapper.doFilter(ClientCertificateMapper.java:77)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at java.lang.Thread.run(Thread.java:748)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT Caused by: org.springframework.core.serializer.support.SerializationFailedException: Failed to serialize object using DefaultSerializer; nested exception is java.io.NotSerializableException: org.opensaml.saml2.core.impl.NameIDImpl
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.core.serializer.support.SerializingConverter.convert(SerializingConverter.java:68)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.core.serializer.support.SerializingConverter.convert(SerializingConverter.java:35)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.serialize(JdkSerializationRedisSerializer.java:91)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	... 41 common frames omitted
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT Caused by: java.io.NotSerializableException: org.opensaml.saml2.core.impl.NameIDImpl
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.core.serializer.DefaultSerializer.serialize(DefaultSerializer.java:46)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	at org.springframework.core.serializer.support.SerializingConverter.convert(SerializingConverter.java:63)
2017-10-30T13:40:40.14-0700 [APP/PROC/WEB/0]OUT 	... 43 common frames omitted
```

**Comment by mraible** [comment]
I googled for your error, and it looks like [setting property forcePrincipalAsString to true in the SAMLAuthenticationProvider might solve the issue](http://forum.spring.io/forum/spring-projects/security/saml/128697-notserializableexception-org-opensaml-saml2-core-impl-nameidimpl).

**Comment by ja3per** [comment]
@loktar I use this way to resolve this issue. you can refer to.
1. use this pom
` <dependency>
            <groupId>org.springframework.security.extensions</groupId>
            <artifactId>spring-security-saml-dsl</artifactId>
            <version>1.0.2.RELEASE</version>
        </dependency>`
2. add forcePrincipalAsString() in SecurityConfiguration
`  http.authorizeRequests()
            .antMatchers("/saml*").permitAll()
            .anyRequest().authenticated()
            .and()
            .apply(saml())
            .webSSOProfileConsumer(webSSOProfileConsumer)
            .serviceProvider()
            .keyStore()
            .storeFilePath(keyStoreFilePath)
            .password(password)
            .keyname(keyAlias)
            .keyPassword(password)
            .and()
            .protocol("https")
            .hostname(String.format("%s:%s", "localhost", port))
            .basePath("/")
            .and()
            .identityProvider()
            .metadataFilePath(metadataUrl)
            .and()
           **.forcePrincipalAsString();**`
